### ISSUE TITLE
Install dependency error

### ISSUE THREAD

**Issue by DavidLeng001** [balancer-labs/balancer-v2-monorepo#1005]
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide @ethersproject/providers (p3b7db), requested by @balancer-labs/typechain
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide @ethersproject/providers (p6e2ee), requested by @typechain/ethers-v5
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide ethers (p0aa6e), requested by @balancer-labs/typechain
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide ethers (p8b50d), requested by @typechain/ethers-v5
➤ YN0002: │ @balancer-labs/balancer-js@workspace:pkg/balancer-js doesn't provide tslib (p042b4), requested by @rollup/plugin-typescript
➤ YN0060: │ @balancer-labs/v2-asset-manager-utils@workspace:pkg/asset-manager-utils provides prettier (p4e59a) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0002: │ @balancer-labs/v2-deployments@workspace:pkg/deployments doesn't provide ethers (pe72fc), requested by @nomiclabs/hardhat-ethers
➤ YN0060: │ @balancer-labs/v2-distributors@workspace:pkg/distributors provides prettier (p25313) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-linear@workspace:pkg/pool-linear provides prettier (pa4f50) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-stable-phantom@workspace:pkg/pool-stable-phantom provides prettier (pc6725) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-stable@workspace:pkg/pool-stable provides prettier (pa4a87) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-utils@workspace:pkg/pool-utils provides prettier (p4b19b) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-pool-weighted@workspace:pkg/pool-weighted provides prettier (p5f74a) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-solidity-utils@workspace:pkg/solidity-utils provides prettier (p45610) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-standalone-utils@workspace:pkg/standalone-utils provides prettier (p5ec8b) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0060: │ @balancer-labs/v2-vault@workspace:pkg/vault provides prettier (p15dce) with version 2.2.1, which doesn't satisfy what solhint-plugin-prettier requests
➤ YN0002: │ typechain@npm:3.0.0 doesn't provide typescript (p4ba7f), requested by ts-essentials
➤ YN0002: │ typechain@npm:5.1.1 doesn't provide typescript (p861d0), requested by ts-essentials
➤ YN0002: │ typechain@npm:5.1.2 doesn't provide typescript (p2a387), requested by ts-essentials
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 279ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 644ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 921ms
➤ YN0000: Done with warnings in 2s 999ms

npm version: 8.1.3 
node version: 17.0.1
yarn version:2.4.1
system: MacOS monterey, Mac mini M1

**Comment by david-leng** [comment]
It looks like something is missing from the dependency file

**Comment by nventuro** [comment]
Hi @david-leng! Thanks for reporting this.

Did you run into this problem when installing dependencies on the repo for local development, or when installing one of the packages bundled here? In particular, the `balancer-js` package lists `peerDependencies` to not force users on a specific version of ethers: one must be supplied manually.

**Comment by david-leng** [comment]
First thanks for your reply. @nventuro
It happened when i installing dependencies on the repo for local development.

**Comment by david-leng** [comment]
> Hi @david-leng! Thanks for reporting this.
> 
> Did you run into this problem when installing dependencies on the repo for local development, or when installing one of the packages bundled here? In particular, the `balancer-js` package lists `peerDependencies` to not force users on a specific version of ethers: one must be supplied manually.

First thanks for your reply. @nventuro
It happened when i installing dependencies on the repo for local development.

**Comment by nventuro** [comment]
I see, thank you. Yes, there are some things to sort out regarding peer dependencies (we've been trying to address them but it is actually a bit of a suble problem), however despite those warnings your local installation will be complete and you will be able to successfully develop or run tests, as you can see from our CI runs.
