### ISSUE TITLE
Remove MultiDistributorAuthorization

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#1006]
MultiDistributor is permissionless as of #960, so we don't need this module at all.

**Comment by TomAFrench** [comment]
This seems to conflict with #970.

**Comment by nventuro** [comment]
You're right, I forgot about that! We'll follow the same pattern `VaultAuthorization` follows, except we'll check for relayer permissions in the Vault. Closing!
