### ISSUE TITLE
Review whether we want to support callbacks for claims and exits

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/balancer-v2-monorepo#1036]
Having callbacks on the staking contracts are looking a little out of place and throwing up some question marks:

- breaking pattern of main claiming/exiting interface functions
- potentially unlikely to be used (EOAs likely to claim from our interface which won't use callbacks)
- relayers being able to claim on behalf of users opens up the possibility of users just using the batch relayer

We should take some time to decide whether they should exist in the final iteration of the staking contracts.

**Comment by nventuro** [comment]
Closing as the milestone itself is being closed.
