### ISSUE TITLE
Create simplified endpoints for common staking actions

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/balancer-v2-monorepo#1038]
We current expose a lot of functionality in the `stake`/`unstake` interfaces with custom senders, recipients and methods of transferring tokens to the staking contract.

This results in transactions interacting with the staking contract being quite calldata heavy unnecessarily. For example 99% of users will be their own assets and sending them to the same address so including their address twice in calldata is wasteful (it can just be read from msg.sender). This is fine on L1 but on rollups calldata makes up the vast majority of transaction costs so it's worth optimising for extremely simple function signatures if possible.

We should identify these main usecases and remove unnecessary arguments for these.

**Comment by nventuro** [comment]
Closing as the milestone itself is being closed.
