### ISSUE TITLE
MultiDistributor: Distinguish between distributions and distribution channels

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/balancer-v2-monorepo#1048]
We currently have some terminology overloading between distributions (a tuple of staking token, distribution token, and owner which stakers can subscribe to for rewards) and distributions (a single deposit of distribution token to be distributed to stakers). This will lead to misunderstandings and difficulty in reasoning about the code by outside parties.

We already have the concept of distribution channels in the Merkle orchard which is a natural fit for the first definition. We should rename any of this usage of "distribution".

**Comment by nventuro** [comment]
Closing as the milestone itself is being closed.
