### ISSUE TITLE
Proposal: Make interfaces compliant with version 0.8

### ISSUE THREAD

**Issue by musecrypto** [balancer-labs/balancer-v2-monorepo#1072]
It seems like currently dependent projects cannot import the interfaces because they define the version as `^0.7.0`. We propose a change of all interface versions to `>=0.7.0` to allow for compilation on solidity 0.8.0 or higher.

**Comment by nventuro** [comment]
Thanks for the request!

We're likely going to tackle this very soon, and potentially also migrate a large part of the codebase over to 0.8 in order to take advantage of new features.
