### ISSUE TITLE
Choose gauge version and make proxyable

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#1081]
A quick scan of [Curve deployments](https://curve.readthedocs.io/ref-addresses.html#liquidity-gauges) seems to indicate there are currently no V4 gauges live. We should look at the differences between V3 and V4 and pick whichever makes the most sense.

Additionally, it seems like we'll need to remove its constructor and transform it into an initializer function, since contract factories are not a thing in Vyper.

**Comment by TomAFrench** [comment]
> A quick scan of Curve deployments seems to indicate there are currently no V4 gauges live. 

This seems to be out of date. [Here is a V4 gauge in production.](https://etherscan.io/address/0x1e212e054d74ed136256fc5a5dddb4867c6e003f#code
)

From looking at the diffs between the two gauge versions the main differences seem to be:
- A number of addresses are hardcoded for gas efficiency reasons
- Delegated boosts are supported (note no usage of veBoost in V3)
- V3 relies on a separate staking contract for rewards whereas V4 holds the rewards on the gauge itself. As a knock on effect LP tokens must be transferred into/out of this staking contract on deposits/withdraws, increasing costs.

From this it looks like V4 is definitely the way to go.

**Comment by TomAFrench** [comment]
Alternatively we have [this](https://github.com/curvefi/curve-factory-crypto/blob/master/contracts/LiquidityGauge.vy) which 

- Adds permit with eip1271 support
- Has the initalizer already
- Packs the inflation data to save some storage reads

We'll need to make some modifications around the admin as that's not suitable for us but otherwise it'll save us a bunch of work.

**Comment by nventuro** [comment]
Note that the contract linked does not have the same source code as the [V4 gauge in the master branch](https://github.com/curvefi/curve-dao-contracts/blob/master/contracts/gauges/LiquidityGaugeV4.vy), there seem to be a few different methods garding ownership transfer.

**Comment by TomAFrench** [comment]
> Note that the contract linked above does not have the same source code as the V4 gauge in the master branch, there seem to be a few different methods garding ownership transfer.

These changes are due to these gauges having a shared admin which is stored on the factory contract to avoid performing N updates to the admin.
