### ISSUE TITLE
Consider allowing the minter to claim rewards other than BAL from gauges

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/balancer-v2-monorepo#1113]
Currently to claim all of their rewards a user has to:

1. call to the BalancerMinter to claim BAL rewards for all gauges
2. make a separate call to each gauge to claim any other rewards for that gauge.

Step 2 can be improved by having a contract which allows a user to call into many gauges in a single transaction (anyone can claim on a user's behalf so there's no permissioning necessary here). **We'll need this on L2**

What's undecided is whether we want to allow the minter to trigger these reward claims to handle both steps 1 and 2 in a single transaction.

**Comment by nventuro** [comment]
Could we have the user call `setMinterApproval` on the BatchRelayer, and use it to combine both steps?

**Comment by TomAFrench** [comment]
Yes, that would work.

**Comment by nventuro** [comment]
...could we add `setMinterApprovalWithSignature`? :sweat_smile:
