### ISSUE TITLE
Add pool factory killswitch

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#1127]
It'd be interesting to be able to deprecate old pool factories entirely, by preventing them from creating more Pools. This would've proven useful with LBPs, for which we had to [release a hotfix](https://github.com/balancer-labs/balancer-v2-monorepo/pull/1049), but still see usage of the old, deprecated factories.

Note that #1049 includes such a killswitch.

**Comment by EndymionJkb** [comment]
There is a PR addressing this #1281, but we are likely going to simply incorporate it directly into our base classes, rather than trying to make it a Mixin, since we likely don't want any standard factories that lack this feature.
