### ISSUE TITLE
Collect and populate roles for Authorizer migration task

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#1219]
See [this review comment](https://github.com/balancer-labs/balancer-v2-monorepo/pull/1173#discussion_r830144653).

**Comment by nventuro** [comment]
These are not just the action ids, but also their delays.

**Comment by TomAFrench** [comment]
We've collected these roles and they just need to be input into the deployment task at this point. Closing this in favour of #1451
