### ISSUE TITLE
Consider resetting Managed Pool denormalisation factor on weight updates

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/balancer-v2-monorepo#1255]
#677 allows the sum of the weights of all tokens in a Managed Pool to diverge from 1e18 as some weight will disappear when removing tokens and new weight will appear when adding tokens. The total weight of the tokens in the pool is then tracked as `_denormWeightSum`.

By repeatedly adding/removing tokens and updating weights it's possible for a determined pool manager to push `_denormWeightSum` to the extreme values of `0` or `_MAX_DENORM_WEIGHT = 1e22`. At this point certain operations will begin failing and restoring the pool will require considerable knowledge of the inner workings of the pool.

It's then potentially worth periodically resetting `_denormWeightSum` whenever we hold the pool's normalised weights in memory and are about to write them back to storage. A good time to do this would be in [_startGradualWeightChange](https://github.com/balancer-labs/balancer-v2-monorepo/blob/571d10ec69f2c4450d2c2c7812fc69d7043f1b7d/pkg/pool-weighted/contracts/smart/ManagedPool.sol#L606-L632)

**Comment by nventuro** [comment]
This was implemented in https://github.com/balancer-labs/balancer-v2-monorepo/pull/1768
