### ISSUE TITLE
Implement sensible limits on ManagedPool values, or remove them

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#1263]
We don't quite know what values might be good max values for e.g. AUM fees. Perhaps we could not have limits at all and leave that up to the controller.

**Comment by TomAFrench** [comment]
Rab's thoughts on max swap fees.

> Target: 99%
> Compromise: 95%
> Threshold: 90%

https://github.com/balancer-labs/balancer-v2-monorepo/pull/1846#discussion_r983640596
