### ISSUE TITLE
Introduce BaseStablePool

### ISSUE THREAD

**Issue by EndymionJkb** [balancer-labs/balancer-v2-monorepo#1344]
PR #1074 refactors the stable pool hierarchy in a manner similar to the weighted pools. In particular, it separates the "Oracle" bits from the "Rate Provider" bits. Effectively, all stable pools are "meta" pools, since even the regular 5-token StablePool will have Rate Providers. The current MetaStablePool can then be renamed OracleStablePool (parallel to OracleWeightedPool).

**Comment by nventuro** [comment]
With the removal of MetaStablePool, we don't need a base one as there'll just be onlly one.
