### ISSUE TITLE
The Ethereum Address link of readme seems incorrecot

### ISSUE THREAD

**Issue by ShawnWu0x** [balancer-labs/balancer-v2-monorepo#1381]
The Ethereum Address link under   
https://github.com/balancer-labs/balancer-v2-monorepo/tree/master/pkg/deployments/tasks/20220609-stable-pool-v2#readme seems incorrect, it was linked to the same link of polygon address

**Comment by nventuro** [comment]
Thanks for reporting this! Fixed in 744c8b51f641a70278785340f3a955cdb7775387
