### ISSUE TITLE
Add `getInvariant` getter to PhantomStablePool

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/balancer-v2-monorepo#1494]
All weighted pools have a `getInvariant` function which they inherit from `BaseWeightedPool`:
https://github.com/balancer-labs/balancer-v2-monorepo/blob/5d8222df482fbcd7b76f1a345c2dfa8c63e8bace/pkg/pool-weighted/contracts/BaseWeightedPool.sol#L83-L95

It looks like we don't have any such function for any of the stable pool flavours. The closest we get is the `getRate` function which exposes `invariant / virtualSupply`

https://github.com/balancer-labs/balancer-v2-monorepo/blob/2b70ac0863a654b863fbd105d0a5a48caaa81478/pkg/pool-stable-phantom/contracts/StablePhantomPool.sol#L1273-L1287

https://github.com/balancer-labs/balancer-v2-monorepo/blob/2b70ac0863a654b863fbd105d0a5a48caaa81478/pkg/pool-stable-phantom/contracts/StableMath.sol#L524-L533

It seems like we could easily refactor this to provide getters for both values pretty easily. That said I'm not sure how much value this would add other than standardisation with WeightedPools.

**Comment by nventuro** [comment]
I don't see much reason for exposing these tbh other than for testing purposes, but even that has some maintenance burden (e.g. remembering to apply scaling factors etc). I wouldn't be against outright removal.

**Comment by nventuro** [comment]
We chose not to do this.
