### ISSUE TITLE
Remove return values from relayer library operations

### ISSUE THREAD

**Issue by jubeira** [balancer-labs/balancer-v2-monorepo#1753]
As stated in https://github.com/balancer-labs/balancer-v2-monorepo/issues/936#issue-1025753042, in most cases we are not using the return values.

We do want to preserve the mechanism in `multicall` to be able to peek chained references (see #1509), but we should remove the return values from the functions that have still them for consistency.

**Comment by nventuro** [comment]
@johngrantuk this is something that may affect you. If you're relying on e.g. `swap`'s return value in static calls, you'll need to migrate to the new `peek` function to read its result.
