### ISSUE TITLE
Pay out due external fees before supply is used

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#1813]
Before joins, exits, add/remove, etc., or in general any operation that either affects the supply or reads it, we should pay due external fees (protocol + manager).

**Comment by nventuro** [comment]
We should now be ready to review that this is true.

**Comment by jubeira** [comment]
Visual review in current master https://github.com/balancer-labs/balancer-v2-monorepo/tree/2e27c075ce3c82521e3dccd4988606558306622e: looks ok.

- `join`: https://github.com/balancer-labs/balancer-v2-monorepo/blob/2e27c075ce3c82521e3dccd4988606558306622e/pkg/pool-weighted/contracts/managed/ManagedPool.sol#L416
- `joinSwap`: https://github.com/balancer-labs/balancer-v2-monorepo/blob/2e27c075ce3c82521e3dccd4988606558306622e/pkg/pool-weighted/contracts/managed/ManagedPool.sol#L140
- `exit`: https://github.com/balancer-labs/balancer-v2-monorepo/blob/2e27c075ce3c82521e3dccd4988606558306622e/pkg/pool-weighted/contracts/managed/ManagedPool.sol#L506
- `exitSwap`: https://github.com/balancer-labs/balancer-v2-monorepo/blob/2e27c075ce3c82521e3dccd4988606558306622e/pkg/pool-weighted/contracts/managed/ManagedPool.sol#L152
- `addToken`: https://github.com/balancer-labs/balancer-v2-monorepo/blob/2e27c075ce3c82521e3dccd4988606558306622e/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol#L718
- `removeToken`: https://github.com/balancer-labs/balancer-v2-monorepo/blob/2e27c075ce3c82521e3dccd4988606558306622e/pkg/pool-weighted/contracts/managed/ManagedPoolSettings.sol#L821

I'll take a stab at writing some tests for it.

**Comment by jubeira** [comment]
Tests are already in place for joins / exits / joinSwaps / exitSwaps here: https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/pool-weighted/test/ManagedPool.test.ts#L677

And for add / remove tokens here: https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/pool-weighted/test/ManagedPoolSettings.test.ts#L1239

Maybe we can close this one?
