### ISSUE TITLE
Create a pool with one token

### ISSUE THREAD

**Issue by dmf7z** [balancer-labs/balancer-v2-monorepo#194]
This exercise is to verify that it should be possible to create a `one token pool`. One scenario proposed by @nventuro where someone would want a pool like that, is if they do not desire to provide liquidity for swapping but still put a token to work in an investment manager. 

For example, it should be possible to create a DAI token that its main purpose is to provide 100% DAI to the investment manager it picks (having zero cash always). The pool must always revert on a vault swap.

**Comment by nventuro** [comment]
Closing as we already know this works.
