### ISSUE TITLE
Running tests on pool-weighted fails.

### ISSUE THREAD

**Issue by LinuxIsCool** [balancer-labs/balancer-v2-monorepo#2011]
37 tests fail with `HardhatError: HH700: Artifact for contract "AuthorizerAdaptor" not found.`

Steps to reproduce:
```
git clone --recurse-submodules https://github.com/balancer-labs/balancer-v2-monorepo.git
nvm install 14.18.0
cd balancer-v2-monorepo/
yarn
yarn build
cd pkg/pool-weighted/
yarn test
```

Note that all fuzz-tests pass when running `yarn test-fuzz`

**Comment by TomAFrench** [comment]
> nvm install 14.18.0

Can you check that you're actually using this version? afaik after `nvm install x` you need to follow it up with `nvm use x`.

**Comment by TomAFrench** [comment]
I'm going to close this issue. If you're still running into this issue then feel free to reopen.
