### ISSUE TITLE
Resolve Vyper download CI issues

### ISSUE THREAD

**Issue by EndymionJkb** [balancer-labs/balancer-v2-monorepo#2144]
Suggestion was to upgrade the hardhat-vyper version:

https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-vyper%403.0.2

**Comment by jubeira** [comment]
Apparently it still sometimes fails after the update. We should check if they publish a new version; the issue seems to be around there.
