### ISSUE TITLE
Redeploy batch relayer in L2s with reference to the pseudo minter

### ISSUE THREAD

**Issue by jubeira** [balancer-labs/balancer-v2-monorepo#2493]
The reference to the balancer minter in the batch relayer is immutable, and is currently `address(0)` in the L2s.

We should redeploy in those cases pointing to the pseudo minter.

**Comment by nventuro** [comment]
We are not redeploying this as the current relayer already has permissions and is widely used. If anything we'd deploy a new relayer (either the same code or an updated version with new features), and we'd use non-zero inputs for the minter.
