### ISSUE TITLE
Improve deployment procedure

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#534]
We're currently relying on the [hardhat-deploy-ethers](https://github.com/wighawag/hardhat-deploy-ethers) plugin, which is suitable given that current needs are simple. Moving forward, we will need a more robust and flexible solution.

A good candidate is [Hardhat Ignition](https://github.com/nomiclabs/hardhat-ignition), developed by the core Hardhat team (though still under development). Alternatively, we could always have our own custom setup.

Desirable features:
 - have an easy-to-use registry of mainnet and testnet deployments
 - perform local deploys on top of forked live chains and run tests over them
 - perform live deploys
 - test configuration of live deploys
 - perform tests on forked live chains

**Comment by TomAFrench** [comment]
Closing this as we have moved to the new deployment method now.
