### ISSUE TITLE
Make large LPs rebalance Asset Managers on join/exit

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#576]
There are two things that can cause an Asset Manager to be unbalanced (far from its target investment percentage):
 - large price swings, which derive in cash moving from one token to the other via swaps
 - large LPs joining or existing, increasing or decreasing total cash

While the former is dependent on 'the market', the latter can be triggered by independent actors, opening up griefing vectors. We should prevent this from happening by making large joins or exits rebalance the Asset Manager. Note that this is _not_ the same as making sure the Pool has enough cash to support a large exit.

A slight complication is that the Pool's balances are altered _after_ the join/exit hook finishes execution, so rebalancing after this happens might prove tricky.

**Comment by TomAFrench** [comment]
The vault's re-entrancy guards prevent us from actually doing any rebalancing.

I think the only avenues we can go down on this is to:
- block withdrawals that reduce cash below a certain buffer.
- on large deposits just notify the asset manager that a large deposit has occurred and no fees should be paid out on the next rebalance, etc.

Alternatively we can make the asset manager keep a track of the TVL of the pool and if there are any large changes between rebalances then it works on the assumption that it's being manipulated.

**Comment by nventuro** [comment]
Ah, you're absolutely right about the reentrancy protection. That pretty much means that we cannot really do anything in the join/exit hooks.


>block withdrawals that reduce cash below a certain buffer.

I'm not sure we'd want to do this: it would make exiting very difficult, and doesn't solve the problem with joins.

>on large deposits just notify the asset manager that a large deposit has occurred and no fees should be paid out on the next rebalance, etc.

This (and the TVL suggestion, though I think that might require price oracles?) could work to prevent attacks, yes. But it'd be  fantastic if the attack was impossible in the first place because the join/exit rebalanced, which would additionally mean that we'd get autorebalancing.

----
The only approach I can think of that would serve this purpose is an external contract that first performs the join/exit, and then calls the Asset Manager. It would have to be a relayer however, which would mean large LPs need to approve it. And I am not sure we would be able to make the Pool enforce that the LP is joining via this relayer.

**Comment by TomAFrench** [comment]
> I'm not sure we'd want to do this: it would make exiting very difficult, and doesn't solve the problem with joins.

Yeah, it's not pretty. A relayer which handles this situation would be needed.

> This (and the TVL suggestion, though I think that might require price oracles?) could work to prevent attacks, yes. But it'd be fantastic if the attack was impossible in the first place because the join/exit rebalanced, which would additionally mean that we'd get autorebalancing.

I think the total supply of the BPT token would be a sufficient proxy. If the asset manager sees a large change in the total supply then there have been large in/outflows from the pool causing any over/under-investment. Agreed on autorebalancing being best.

**Comment by TomAFrench** [comment]
One solution that's less drastic than "no fees after a large deposit" is to allow the critical percentages to float with deposits/withdrawals and have a ramping mechanism similar to #577. 

Consider a pool which is at an investment level between the two critical percentages (non-critical range). We can track the net effect of deposits/withdrawals and translate the non-critical range such that a whale depositing a large amount of tokens into cash causes the non-critical range to drop to maintain the investment level relative to these two points.

e.g. Pool has critical percentages at 40% and 60%. A large deposit drops the investment level to 25% from 50%. The effective critical percentages are now 15% and 35%.

We can then slowly bring the non-critical range back up to its original position over time. Should any rebalance occur we immediately bring the non-critical range back to its original position.

---
I think an equivalent formulation is to say "new funds aren't considered for the purposes of fees until they are first included in a rebalance".

**Comment by nventuro** [comment]
Ohh interesting. I think something like that could work, yes. However, it might be better to first explore all possibilities re. autorebalancing on join/exit, to avoid introducing all of this complexity in the reward granting model (which is _the_ thing we want to make sure is not gameable).

**Comment by nventuro** [comment]
Superceded by #604
