### ISSUE TITLE
Constrain altering Asset Manager settings

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#577]
The target managed percentage, critical percentages, payout rate, etc., are all quite sensible parameters. We should limit damage done by a malicious actor with power to change these values.

A simple idea for the percentages is to change them via a ramp (see #394), with a maximum slope value.

**Comment by gtaschuk** [comment]
I think we should revert if an edit to the managed percentage/critical percentage causes a cash balance to fall outside of the critical buffer

**Comment by nventuro** [comment]
What would be the reasoning behind that? Preventing the percentage setter from claiming rewards?

**Comment by nventuro** [comment]
We partially tackled this in https://github.com/balancer-labs/balancer-v2-monorepo/pull/651. Now that we don't have payouts anymore, I believe this configuration is not critical anymore.
