### ISSUE TITLE
Use error codes consistently

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#583]
The Vault and Pools rely on [`BalancerErrors`](https://github.com/balancer-labs/balancer-core-v2/blob/master/pkg/solidity-utils/contracts/helpers/BalancerErrors.sol) and `_require()` for revert reasons to reduce bytecode size usage, and will likely continue doing so in the future as Pools have more and more features. The helpers in the `solidity-utils` package also use this method, since they are imported by the other contracts.

Moving forward, I'd suggest dropping `require` outright from the entire codebase, and committing to only use `_require()`, even in contracts that are not bytecode-size constrained. Some usage of `_require()` will be present nonetheless just by reusing `solidity-functions`: it seems like it'd be a good idea to be consistent in this regard.

**Comment by gtaschuk** [comment]
I think we will have an increasing number of pools, asset managers, distributors etc with increasingly varied implementations, created by bLabs and by the community.  I think it's inevitable that these implementations will require an increasingly varied set of errors.  The list of `BalancerErrors` could get quite lengthy...

Frankly, while `_require()` was necessary to reduce bytecode size, all the cross-referencing is inconvenient for developers.  If possible, I think we should offer a hardhat plugin for reporting something informative in the console.

IMHO we should use `BalancerErrors` in the vault, and potentially in base classes but I don't see much reason to use them in non-bytecode constrained contracts if the consistency it enforces feels like a compromise.

**Comment by nventuro** [comment]
Yeah, a massive BalancerErrors wouldn't be a great idea. I guess you could argue that, even if a base layer does use `_require()` (e.g. `solidity-utils`), we don't need to stick to those in upper layers if it means a simpler user experience. It's not like all revert reasons will be error codes anyway since there's a bunch of external contracts that a transaction might interact with.

I think it'd be good idea though to do use `_require` in these base libraries, as that would otherwise impose higher bytecode size restrictions on other contracts that reuse them.

**Comment by nventuro** [comment]
You both raise good points, thanks. Does keeping `_require` in e.g. `solidity-utils` make sense to you, so that any contracts that use those don't get bytecode intensive revert reasons?
