### ISSUE TITLE
Implement 'where' field in Authorizer

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#587]
The current Authorizer only deals with action IDs (roles), and ignores the `where` field in the request entirely. The revamped version should use this paramater, letting governance grant permission for actions to be performed on only some contracts and not all of them.

**Comment by facuspagnuolo** [comment]
@nventuro isn't this one closed by #980 ?

**Comment by nventuro** [comment]
Indeed!
