### ISSUE TITLE
Consider using Authorizer instead of onlyOwner for reward distributors

### ISSUE THREAD

**Issue by gtaschuk** [balancer-labs/balancer-v2-monorepo#658]
https://github.com/balancer-labs/balancer-v2-monorepo/pull/647#discussion_r654090215

I have done some work on this pattern but think we should PR separately from the linked PR to analyze it in isolation.

My gut reaction is that it's not a clear improvement, and adds significant complexity to this pattern.  It seems we're not using this pattern extensively elsewhere.

**Comment by nventuro** [comment]
We need to think on how to structure this some more, but the reason why we'd want to connect the distributor to the Authorizer is to have a single source of truth on Balancer Governance.

**Comment by nventuro** [comment]
The current iteration of the contract uses the Authorizer under the hood.
