### ISSUE TITLE
Add signature approval to BatchRelayer

### ISSUE THREAD

**Issue by TomAFrench** [balancer-labs/balancer-v2-monorepo#670]
Currently we require a separate call to approve the `RebalancingRelayer`, we should explore a `approveRelayerAndCall` type flow which we can mix into relayers such as this.
https://github.com/balancer-labs/balancer-v2-monorepo/blob/e29c13a6236bc7ea9c38f73bbb23920ae391f9eb/pkg/asset-manager-utils/contracts/RebalancingRelayer.sol#L63-L74

**Comment by nventuro** [comment]
Would it be enough to add an `approveRelayer` function that does `vault.setRelayerApproval(msg.sender, this, true) + signature` and make the contract `Multicall`?

**Comment by nventuro** [comment]
(otherwise we'd need to also do e.g. `approveAndExit`)

**Comment by nventuro** [comment]
(closed by mistake)

**Comment by TomAFrench** [comment]
Yeah, that's another way of implementing it. `approveAndCall` would be a single call simplification of that case rather than having an extra function for each action.

**Comment by TomAFrench** [comment]
We could pull these from #594 and create a `BaseRelayer` which just has the approval + multicall and RebalancingRelayer could just inherit from that.

**Comment by nventuro** [comment]
Moving to the BatchRelayer milestone. Relayed to #689

**Comment by nventuro** [comment]
BatchRelayer can already do this.
