### ISSUE TITLE
Support more than 8 tokens in WeightedPools

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#674]
Investment Pools require more than 8 tokens: we need to support at least 20. With the new SplitCodeFactory, usage of `immutable` state variables is less of a concern, so in theory we could just extend the list to a larger size.

Alternatively, we could store tokens in a mapping (or `EnumerableSet`), which would require changing some other things. The Pools don't actually access their list of tokens all that much, they mostly rely on the tokens to retrieve token-related properties (e.g. `if (token == _token0) return _weight0;`), so this might require some experimentation to see what interface makes the most sense. It might be e.g. a good idea to pack a token's scaling factor with other information such as its weight paramaters.

Note that, if we want for tokens to be added and removed, `immutable` cannot be used at all.

**Comment by nventuro** [comment]
@EndymionJkb you mentioned you gave this a go: how did you handle scaling factors?

**Comment by EndymionJkb** [comment]
_scalingFactor(token) and _scalingFactors() are virtual at the BasePool level, implemented in FixedTokenPool has they currently are in BasePool, and then overridden with different storage in BaseSmartWeightedPool (e.g., mapping of token -> weight + scaling)

**Comment by nventuro** [comment]
Implemented in #738.
