### ISSUE TITLE
Add Management Pool fees

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#676]
These are fees that are charged by Pool administrators, independent of protocol fees. The mechanism we'll use for collecting these fees will likely be a new exit kind, where the sender (or recipient? both?) are permissioned accounts, and tokens are sent for no BPT, or a special join where new BPT is minted for no tokens.

A naive model would mean that LPs will be better off joining immediately after fees are collected, and exiting immediately before, but if fees are expected to be very low this might be fine. Alternatively, we could perform a type of accounting similar to the one we do with protocol fees, avoiding these issues.

Something else to discuss is what sort of fees we could support. At least two have been considered:
 - a 'streaming' fee, which would grant a percentage of the Pool's total holdings (e.g. a yearly 2% of total managed funds)
 - a 'performance' fee, in the form of a percentage of swap fees (the only 'performance' metric)

If we're interested in both, for simplicity's sake I believe we should handle both at once (instead of having two flavors).

The 'performance' fee is somewhat straightforward, as it is not too different from regular protocol fees. The 'streaming' case is more interesting, as we'd likely need to track BPT changes over time (in joins and exits), e.g. in an accumulator.

**Comment by nventuro** [comment]
#814  impelemented the 'performance fee', albeit in a less-than-optimal manner for pools with multiple tokens: we'll need to do some more research on the math to find a more gas efficient implementation (e.g. one that mints BPT to the manager).

**Comment by EndymionJkb** [comment]
As of PRs #1163, #1164, #1214 (after some infrastructure work in #1111), managed pools pay management fees (both swap and AUM kinds) in BPT.
