### ISSUE TITLE
Let Pools register and deregister tokens

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#677]
A big limitation when it comes to token registration and deregistration is that a) registered tokens begin with 0 balance, and b) tokens must have 0 balance to be deregistered. This is a problem because WeightedPools cannot have 0 balances in any tokens: that would lead to an invariant of zero, which is disallowed. Moreover, Pools cannot register or deregister tokens while in a join/exit hook, as the Vault is non-reentrant. Therefore, we need to seed new tokens (join) and remove old ones (exit), but relying on non-standard mechanisms.

The permissioned party that will be able to perform this action will supply the newly added tokens or get the removed ones: the Pool will make no assumptions about where they come from or go to. See #675 for risk mitigation.

A simple approach that could work would be to perform the entire process atomically as a sort of script, either by having the Pool reenter itself or by using a trusted auxiliary contract (say, deployed at Pool creation). I'll explain this in terms of an auxiliary contract (aux), as I find that easier to understand.

When adding tokens, aux first notifies the Pool that this is about to happen. The Pool performs any required maintenance tasks, e.g. pay due protocol fees, and registers the new token and weights. aux then performs a special join that bypasses invariant computations with the current balances (as would be needed for e.g. protocol fee computation) since one of them is zero, receives the tokens minting no BPT in exchange, and verifies the process finished correctly.

Note that, because aux performs both actions in sequence, the fact that the Pool is temporarily in an inconsistent state that e.g. might cause swaps to fail is not a problem. We could extend this to perform more steps, or add additional correctness checks at the end.

Token removal would be similar, except a special exit for no BPT would drop a balance to zero, folllowed by the actual deregistration and weight updating.

**Comment by nventuro** [comment]
With #876, risk mitigation is much less of a concern at this level.

**Comment by EndymionJkb** [comment]
Added with PRs #1131 and #1108
