### ISSUE TITLE
Allow for large exits on AM Pools

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#687]
Currently, large exits will trigger a rebalance and require being called via the rebalancing relayer. However, _very_ large exits (for amounts larger than available cash) will outright fail: LPs are forced to perform multiple smaller ones.

We'd want for this to not be the case. In theory, we should be able to have the rebalancing relayer orchestrate the AM returning cash to the Pool, exiting, and then rebalancing. Since there will be a rebalance at the end, how much cash is returned is not really relevant.

If we take this approach, we'd need to introduce a new function in the AM that returns cash, which should only be callable from the Rebalancing Relayer. Note that the relayer would not make a single call but rather potentially ask _all_ AMs to return some cash, so likely the best way to handle this exit function would be to provide an array with `extraCash` amounts.

**Comment by TomAFrench** [comment]
Fixed in #706
