### ISSUE TITLE
Update Asset Manager earnings before all joins and exits

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#695]
The rebalancing relayer must have the Asset Managers update the Pool's total balances _before_ joins and exits to ensure that they are correctly assigned to the current LPs. Otherwise, a large (e.g. flash-loaned) LP could join the Pool and rapidly exit it, stealing all AM earnings since the last update.

This makes relayers mandatory.

**Comment by TomAFrench** [comment]
Fixed in #706

**Comment by TomAFrench** [comment]
(closed by mistake)
