### ISSUE TITLE
how to use singleSwap or BatchSwap in a smart contract?

### ISSUE THREAD

**Issue by KushGoyal** [balancer-labs/balancer-v2-monorepo#792]
I am trying to integrate [single swap](https://docs.balancer.fi/developers/guides/single-swaps) and [batch swap](https://docs.balancer.fi/developers/guides/batch-swaps)

In both the cases I will need `poolId` to perform the swap. But in the whole docs for v2 I cannot find a way to fetch the `poolId` of any pool.

Can you direct me to the correct page where I can see the method to either perform a swap on balancer v2 without the `poolId` or fetch the correct `poolId` based on token addresses.

**Comment by nventuro** [comment]
Hello @KushGoyal, sorry to have taken so long to answer! We typically receive support questions via either Discord or Intercom: this issue slipped through the cracks.

Regarding `poolId`, indeed you need to know before you can make a swap, join or any other Pool operation. For 'canonical' (i.e. non-custom) Pools, you can call the [`getPoolId()`](https://github.com/balancer-labs/balancer-v2-monorepo/blob/stable/pkg/vault/contracts/interfaces/IBasePool.sol#L90) function on the Pool contract to get its ID.
