### ISSUE TITLE
Allowlist BPT Holders

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#793]
Some institutional use cases require that only allowed parties participate in the pool, i.e. hold the BPT. A very simple way to achieve this is at the BPT contract level, without altering Pool logic.

Note that swaps are not affected by this.

**Comment by EndymionJkb** [comment]
PRs #1001 and #1322 create an allowlist for LPs - but does not address holding BPT. The Integrations team is developing a "Permissioned Pool" that does this more comprehensively, but I don't believe this is in scope for the current release of Managed Pools.
