### ISSUE TITLE
Use struct for amplification data in StablePool

### ISSUE THREAD

**Issue by mijovic** [balancer-labs/balancer-v2-monorepo#817]
Instead of using `WordCodec` to decode and encode `bytes32 private _packedAmplificationData;` you can use the compiler's built-in storage packing (https://docs.soliditylang.org/en/v0.8.7/internals/layout_in_storage.html).
So amplification data can be:
```
struct AmplificationData {
    uint64 startValue;
    uint64 endValue;
    uint64 startTime;
    uint64 endTime;
}
AmplificationData private _amplificationData;
```

When using it, looks much more readable, instead of:
```
_packedAmplificationData =
    WordCodec.encodeUint(uint64(startValue), 0) |
    WordCodec.encodeUint(uint64(endValue), 64) |
    WordCodec.encodeUint(uint64(startTime), 64 * 2) |
    WordCodec.encodeUint(uint64(endTime), 64 * 3);
```
would be this:
```
_amplificationData.startValue = uint64(startValue);
_amplificationData.endValue = uint64(endValue);
_amplificationData.startTime = uint64(startTime);
_amplificationData.endTime = uint64(endTime);
```

**Comment by nventuro** [comment]
Hello @mijovic, thanks for opening this issue!

There's actually a good reason to use `WordCodec`, but admittedly we don't do a good job of explaining what it is. There's a comment in [`BalanceAllocation`](https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/vault/contracts/balances/BalanceAllocation.sol#L39) that describes this in some detail:

```
// We could use a Solidity struct to pack these three values together in a single storage slot, but unfortunately
// Solidity only allows for structs to live in either storage, calldata or memory. Because a memory struct still takes
// up a slot in the stack (to store its memory location), and because the entire balance fits in a single stack slot
// (two 112 bit values plus the 32 bit block), using memory is strictly less gas performant. Therefore, we do manual
// packing and unpacking.
```

`WordCodec` falls under the same umbrella: it's always a 256 word that stores all values in the end (as the purpose is for everything to fit in a single storage slot), and in that context there are very real and measurable gas utilization differences when using stack versus memory variables. 

To make matters worse, Balancer pool operations are typically already quite memory intensive. As the cost of using memory in the EVM increases quadratically with its usage, we've found that these gas cost differences are further amplified in these scenarios, which is why we went with the more manual approach of `WordCodec`.

**Comment by mijovic** [comment]
@nventuro Thanks for the answer and clarification. I see your point here. However, it would be nice to have that documented in the same way as `BalanceAllocation`.

In this case, it is also possible to use struct for better readability of the code and still use `WordCodec`, but that would rely on the compiler's storage packing.

**Comment by nventuro** [comment]
Agreed - I added rationale in eb7449ab.

>In this case, it is also possible to use struct for better readability of the code and still use WordCodec

Are you thinking of having struct storage pointers and then read-write to each struct element directly? If so, we've tested this and it unfortunately results in repeated storage accesses (at least, in all paterns we've tried), which translates directly to higher gas costs.

**Comment by mijovic** [comment]
I was thinking more like this:
```
    function _setAmplificationData(
        uint256 startValue,
        uint256 endValue,
        uint256 startTime,
        uint256 endTime
    ) private {
        // solhint-disable-next-line no-inline-assembly
        assembly {
            let value := add(
                add(shl(192, startValue), shl(128, endValue)),
                add(shl(64, startTime), endTime)
            )
            sstore(_amplificationData.slot, value)
        }

        emit AmpUpdateStarted(startValue, endValue, startTime, endTime);
    }

    function _getAmplificationData()
        private
        view
        returns (
            uint256 startValue,
            uint256 endValue,
            uint256 startTime,
            uint256 endTime
        )
    {
        // solhint-disable-next-line no-inline-assembly
        assembly {
            let mask := 0x000000000000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF
            let value := sload(_amplificationData.slot)
            startValue := and(shr(192, value), mask)
            endValue := and(shr(128, value), mask)
            startTime := and(shr(64, value), mask)
            endTime := and(value, mask)
        }
    }
```

But also, I am not sure if this would be better compared to using `WordCodec`

**Comment by nventuro** [comment]
Ah yes, definitely, you could use yul that way. I'd be interested in comparing it to `WordCodec` as it should save gas, but likely not that much - it is the lack of usage of `memory` in `WordCodec` that we were mostly interested in.
