### ISSUE TITLE
Reduce gas cost of Orchard claims

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#885]
Claiming multiple distributions for the same distribution channel should be optimized for: we can follow a pattern similar to the one presented in https://github.com/balancer-labs/balancer-v2-monorepo/pull/842 to achieve this.

**Comment by TomAFrench** [comment]
Appears to be a duplicate of #890

**Comment by nventuro** [comment]
They're not the same, though this one could use with more explaning. This issue is about improving storage layout to have multiple distributions in the same slot, #890 is about optimizing _how_ we access said storage slot to reduce the number of sloads and sstores, i.e. have a single sload and sstore per slot, even if we're processing multiple distributions that would use the same one.
