### ISSUE TITLE
[managed] Add a gradually changing swap fee

### ISSUE THREAD

**Issue by nventuro** [balancer-labs/balancer-v2-monorepo#891]
By replicating in swap fees the behavior we have for linearly changing weights with start and end dates, we could open up a number of very interesting use cases that would make Managed Pools a much more powerful primitive. 

[This blogpost](https://medium.com/balancer-protocol/high-fee-balancer-pools-for-swing-trading-8bc1c169a4c2) goes over the impact larger swap fees have on swaps, the tldr is they effectively increase the spread between buy and sell prices. This means gradually decreasing swap fees can be used to artificially inflate prices and then slowly bring them back, which in turn allows for instant weight changes without value loss due to arbitrageur activity, as the artificially high swap fee would prevent that until prices match market rates. This is also useful for Pools that have swaps disabled for a large part of their lifetime.

**Comment by EndymionJkb** [comment]
Added with PR #1253
