### ISSUE TITLE
MultiDistributor: Rewards might be lost during initialization

### ISSUE THREAD

**Issue by facuspagnuolo** [balancer-labs/balancer-v2-monorepo#969]
I believe this has been carried over since the original implementation of Synthetix and Curve. When a new rewards are added to a distribution there are basically two alternatives:

https://github.com/balancer-labs/balancer-v2-monorepo/blob/c40b9a783e328d817892693bd13b4a14e4dcff4d/pkg/distributors/contracts/MultiRewards.sol#L508-L515

As you can see, when `periodFinish` has been reached, the reward rate of the distribution is set, otherwise it is re-calculated contemplating any leftover rewards. The first case also applies the first time the distribution is rewarded.

This may not be a problem for the original implementation because we could assume users could have staked before the distribution rewards start. However, in our implementation we are introducing the idea of any rewarder creating distributions while having users to opt-in these distributions. Therefore, it is expected for users not to subscribe these distributions before these are created.

The problem is that `updateReward` updates the `lastUpdateTime` even when the supply is zero:

https://github.com/balancer-labs/balancer-v2-monorepo/blob/c40b9a783e328d817892693bd13b4a14e4dcff4d/pkg/distributors/contracts/MultiRewards.sol#L565-L568

This means that the rewards that apply to the period of time that has passed until the first user staked tokens, will not be distributed.

**Comment by TomAFrench** [comment]
I'm tempted to just accept this issue. There's three ways of handling this that I see:

1. On each call to `_globalTokensPerStake` we return whether we're going to apply the update to storage based on whether there's some staked supply.
2. Update the `distribution.duration > 0` check on funding a distributions to `distribution.supply > 0` which requires someone to stake some tokens and subscribe to the distribution before it can be funded.
3. Update the `fundDistribution` function to automatically stake and subscribe with 1 wei for the distribution owner if `distribution.supply == 0`

All of these have some issues associated with them:
1. This imposes an extra cost on every action for something which is irrelevant for 99.9999% of the time.
2. This increases friction for people setting up distributions and just is a bit of a pain in terms of UX.
3. This is pretty nasty as it breaks the proper accounting of staked token balances.

Considering that this works fine as is for Synthetix and Curve, I'd say that it's fine for us.

**Comment by nventuro** [comment]
Closing as the milestone itself is being closed.
