### ISSUE TITLE
MultiDistributor: Rely on vault's authorization module for relayers

### ISSUE THREAD

**Issue by facuspagnuolo** [balancer-labs/balancer-v2-monorepo#970]
Some methods like `stake`, `withdraw`, or `claim` could leverage the idea of relayers through the Vault's authorization module. This means that any third-party could try to execute transactions on someone's behalf by providing a signature or if they are whitelisted as relayers.

**Comment by TomAFrench** [comment]
Implemented in #1006

**Comment by TomAFrench** [comment]
Reopening until we add support for this on all relevant external functions.

**Comment by nventuro** [comment]
Closing as the milestone itself is being closed.
